version: '3.7'

services:
  web:
    image: new-divos/stepik-flask-tutors/web

    build:
      context: .
      dockerfile: docker/web/Dockerfile

    command: gunicorn -b 0.0.0.0:5000 manage:app --access-logfile -
    volumes:
      - stepik_flask_tutors_data:/var/web/data

    environment:
      - FLASK_APP=manage:app
      - FLASK_ENV=production
      - APP_STORAGE_LOCATION=local
      - APP_STORAGE_DIR=/var/app/data
    env_file:
      - ./.env.prod

  nginx:
    image: new-divos/stepik-flask-tutors/nginx

    build:
      context: ./docker/nginx
      dockerfile: Dockerfile

    ports:
      - 8080:80

    depends_on:
      - web

volumes:
  stepik_flask_tutors_data:
