name: stepik-flask-teachers
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - flask=1.1
  - pip
  - pip:
      - flask-bootstrap4
      - flask-migrate
      - flask-sqlalchemy
      - flask-wtf
      - psycopg2-binary
      - gunicorn
