"""empty message

Revision ID: b5f539f5bea7
Revises: 96eb62933fb7
Create Date: 2020-06-19 18:54:07.429147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f539f5bea7'
down_revision = '96eb62933fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('possibility', sa.Enum('PO1_2', 'PO3_5', 'PO5_7', 'PO7_10', name='possibility'), nullable=True),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_requests')
    # ### end Alembic commands ###
